// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Mbf6gG39lGTkhHPT0FysutE16j1JnAw',
    appId: '1:129587485294:web:6689e8e019fc499bd7e47f',
    messagingSenderId: '129587485294',
    projectId: 'facebook-42691',
    authDomain: 'facebook-42691.firebaseapp.com',
    storageBucket: 'facebook-42691.appspot.com',
    measurementId: 'G-YRE6TWQHWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-LmycdtMEejx0n-ms90Ohom9UzR1xDYs',
    appId: '1:129587485294:android:256e52659e1f4220d7e47f',
    messagingSenderId: '129587485294',
    projectId: 'facebook-42691',
    storageBucket: 'facebook-42691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5P-7RcEMHrqmeG0U39LYiiTVFw4hE__A',
    appId: '1:129587485294:ios:4dadeaaed4bc0613d7e47f',
    messagingSenderId: '129587485294',
    projectId: 'facebook-42691',
    storageBucket: 'facebook-42691.appspot.com',
    iosClientId: '129587485294-ijkaug538b12jrkkr30i0nljagdl50hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.heybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5P-7RcEMHrqmeG0U39LYiiTVFw4hE__A',
    appId: '1:129587485294:ios:4dadeaaed4bc0613d7e47f',
    messagingSenderId: '129587485294',
    projectId: 'facebook-42691',
    storageBucket: 'facebook-42691.appspot.com',
    iosClientId: '129587485294-ijkaug538b12jrkkr30i0nljagdl50hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.heybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Mbf6gG39lGTkhHPT0FysutE16j1JnAw',
    appId: '1:129587485294:web:f6078bba67800284d7e47f',
    messagingSenderId: '129587485294',
    projectId: 'facebook-42691',
    authDomain: 'facebook-42691.firebaseapp.com',
    storageBucket: 'facebook-42691.appspot.com',
    measurementId: 'G-3TJLEP4CN4',
  );
}
